version: "3.9"

services:

  db:
    container_name: postgresql_db
    image: postgres
    hostname: postgres-kabum
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=kabum_db

  app:
    container_name: app
    build: .
    entrypoint:
      - uvicorn
      - app.main:app
      - --host
      - 0.0.0.0
      - --port
      - "8000"
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=kabum_db
      - POSTGRES_DB_HOST=postgres-kabum
